/* Generated By:JavaCC: Do not edit this line. SQLCompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 5;
  /** RegularExpression Id. */
  int UPDATE = 6;
  /** RegularExpression Id. */
  int INSERT = 7;
  /** RegularExpression Id. */
  int DELETE = 8;
  /** RegularExpression Id. */
  int SELECT = 9;
  /** RegularExpression Id. */
  int INTO = 10;
  /** RegularExpression Id. */
  int VALUES = 11;
  /** RegularExpression Id. */
  int AS = 12;
  /** RegularExpression Id. */
  int SET = 13;
  /** RegularExpression Id. */
  int WHERE = 14;
  /** RegularExpression Id. */
  int TABLE = 15;
  /** RegularExpression Id. */
  int INDEX = 16;
  /** RegularExpression Id. */
  int SEMI = 17;
  /** RegularExpression Id. */
  int LP = 18;
  /** RegularExpression Id. */
  int RP = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int DOT = 21;
  /** RegularExpression Id. */
  int EQUAL = 22;
  /** RegularExpression Id. */
  int STAR = 23;
  /** RegularExpression Id. */
  int INT = 24;
  /** RegularExpression Id. */
  int STRING = 25;
  /** RegularExpression Id. */
  int ID = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<CREATE>",
    "<UPDATE>",
    "<INSERT>",
    "<DELETE>",
    "<SELECT>",
    "<INTO>",
    "<VALUES>",
    "<AS>",
    "<SET>",
    "<WHERE>",
    "<TABLE>",
    "<INDEX>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"*\"",
    "<INT>",
    "<STRING>",
    "<ID>",
  };

}
